# Generated by Django 4.0.5 on 2022-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_text', models.CharField(max_length=200)),
                ('decrypted_text', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
