# Generated by Django 4.0.5 on 2022-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
